#ifndef __AjoutMatriceDialogue__
#define __AjoutMatriceDialogue__

/**
@file
Subclass of AjoutMatriceDialogue, which is generated by wxFormBuilder.
*/

#include "Dialogs.h"

//// end generated include

/** Implementing AjoutMatriceDialogue */
class AjoutMatriceDialogue : public AjoutMatriceDialogueBase
{
	public:
		/** Constructor */
		AjoutMatriceDialogue( wxWindow* parent );
	//// end generated class members
	
};

#endif // __AjoutMatriceDialogue__
