#ifndef __AjoutMatriceDialogue__
#define __AjoutMatriceDialogue__

/**
@file
Subclass of AjoutMatriceDialogue, which is generated by wxFormBuilder.
*/

#include "Dialogs.h"
#include "Conteneur.h"

//// end generated include

/** Implementing AjoutMatriceDialogue */
class AjoutMatriceDialogue : public AjoutMatriceDialogueBase
{
	public:
		/** Constructor */
		AjoutMatriceDialogue( wxWindow* parent, Conteneur* conteneur );
	//// end generated class members
	protected:
		void SurClicValiderTailleMatrice( wxCommandEvent& event );
		//void SurClicAnnuler( wxCommandEvent& event );
		void SurClicSauver( wxCommandEvent& event );
	private:
		Conteneur* m_conteneur;
};

#endif // __AjoutMatriceDialogue__
